import { Alert, Button, Card, Form, Input, Modal, Popconfirm, Select, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocation, useNavigate } from '@umijs/max';
import { useState } from 'react';
import { AuthGate } from '../components/AuthGate';
import type { OpsRouteKey } from '../config/navigation';
import { opsMerchantApi, type OpsMerchant, type OpsNotification, type OpsOnboarding } from '../services/merchant';

const categories = ['餐饮', '零售', '生活服务', '其他'];

export default function MerchantOperationsPage() {
  const { pathname } = useLocation();
  const key = pathname === '/merchants' ? 'merchants' : pathname === '/onboardings' ? 'onboardings' : pathname === '/notifications' ? 'notifications' : 'todos';
  return <AuthGate routeKey={key as OpsRouteKey}>{key === 'merchants' ? <Merchants /> : key === 'onboardings' ? <Onboardings /> : key === 'notifications' ? <Notifications /> : <Todos />}</AuthGate>;
}

function Merchants() {
  const client = useQueryClient(); const [status, setStatus] = useState<string>(); const [open, setOpen] = useState(false); const [form] = Form.useForm();
  const list = useQuery({ queryKey: ['ops', 'merchants', status], queryFn: () => opsMerchantApi.merchants(status) });
  const refresh = () => client.invalidateQueries({ queryKey: ['ops', 'merchants'] });
  const create = async (value: { ownerUserId: string; merchantName: string; category: string; contactName?: string; contactMobile?: string; remark?: string }) => { try { await opsMerchantApi.createMerchant({ ...value, agreementVersion: 'v4.7.0' }); setOpen(false); form.resetFields(); await refresh(); message.success('代建商户已启用'); } catch (error) { message.error(error instanceof Error ? error.message : '创建失败'); } };
  const toggleLock = async (item: OpsMerchant) => { try { await opsMerchantApi.updateMerchant(item.merchantId, { version: item.version, name: item.name, remark: item.remark, status: item.status, receiveLocked: !item.receiveLocked }); await refresh(); message.success('收款限制已更新'); } catch (error) { message.error(error instanceof Error ? error.message : '操作失败'); } };
  const toggleStatus = async (item: OpsMerchant) => { const status = item.status === 'ACTIVE' ? 'DISABLED' : 'ACTIVE'; try { await opsMerchantApi.updateMerchant(item.merchantId, { version: item.version, name: item.name, remark: item.remark, status, receiveLocked: item.receiveLocked }); await refresh(); message.success('商户状态已更新'); } catch (error) { message.error(error instanceof Error ? error.message : '操作失败'); } };
  return <Card title="商户管理" extra={<Space><Select allowClear placeholder="状态筛选" style={{ width: 130 }} value={status} onChange={setStatus} options={['PENDING', 'ACTIVE', 'REJECTED', 'DISABLED'].map(value => ({ value }))} /><Button type="primary" onClick={() => setOpen(true)}>代建商户</Button></Space>}><Table rowKey="merchantId" loading={list.isPending} dataSource={list.data ?? []} pagination={false} columns={[{ title: '商户号', dataIndex: 'merchantId' }, { title: '名称', dataIndex: 'name' }, { title: '联系人', render: (_, item: OpsMerchant) => `${item.contactName ?? '-'} ${item.contactMobileMasked ?? ''}` }, { title: '状态', render: (_, item: OpsMerchant) => <Tag color={item.status === 'ACTIVE' ? 'green' : 'default'}>{item.status}</Tag> }, { title: '收款', render: (_, item: OpsMerchant) => item.receiveLocked ? <Tag color="red">已限制</Tag> : <Tag color="green">正常</Tag> }, { title: '操作', render: (_, item: OpsMerchant) => <Space><Popconfirm title="确认修改收款限制？" onConfirm={() => void toggleLock(item)}><Button size="small">{item.receiveLocked ? '解除限制' : '限制收款'}</Button></Popconfirm>{['ACTIVE', 'DISABLED'].includes(item.status) ? <Popconfirm title="确认修改商户启停状态？" onConfirm={() => void toggleStatus(item)}><Button size="small">{item.status === 'ACTIVE' ? '停用' : '启用'}</Button></Popconfirm> : null}</Space> }]} /><Modal title="管理员代建商户" open={open} footer={null} onCancel={() => setOpen(false)} destroyOnHidden><Alert type="info" showIcon title="店主必须是已注册且未绑定商户的钱包用户。" /><Form form={form} layout="vertical" onFinish={create} style={{ marginTop: 16 }}><Form.Item name="ownerUserId" label="店主用户 UUID" rules={[{ required: true, type: 'string' }]}><Input /></Form.Item><Form.Item name="merchantName" label="经营名称" rules={[{ required: true, min: 2, max: 40 }]}><Input /></Form.Item><Form.Item name="category" label="类目" rules={[{ required: true }]}><Select options={categories.map(value => ({ value }))} /></Form.Item><Form.Item name="contactName" label="联系人"><Input /></Form.Item><Form.Item name="contactMobile" label="联系电话" rules={[{ required: true, message: '请输入联系电话' }, { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的 11 位手机号' }]}><Input inputMode="numeric" maxLength={11} /></Form.Item><Form.Item name="remark" label="内部备注"><Input.TextArea maxLength={200} /></Form.Item><Button type="primary" htmlType="submit">创建并启用</Button></Form></Modal></Card>;
}

function Onboardings() {
  const client = useQueryClient(); const [reason, setReason] = useState<string>(); const [selected, setSelected] = useState<OpsOnboarding>(); const list = useQuery({ queryKey: ['ops', 'onboardings'], queryFn: () => opsMerchantApi.onboardings('PENDING') }); const refresh = () => client.invalidateQueries({ queryKey: ['ops', 'onboardings'] });
  const approve = async (item: OpsOnboarding) => { try { await opsMerchantApi.approve(item.onboardingId); await refresh(); message.success('已审核通过并回填商户资料'); } catch (error) { message.error(error instanceof Error ? error.message : '审核失败'); } };
  const reject = async () => { if (!selected || !reason?.trim()) { message.warning('请填写拒绝原因'); return; } try { await opsMerchantApi.reject(selected.onboardingId, reason); setSelected(undefined); setReason(undefined); await refresh(); message.success('已拒绝申请'); } catch (error) { message.error(error instanceof Error ? error.message : '审核失败'); } };
  return <Card title="入驻审核"><Table rowKey="onboardingId" loading={list.isPending} dataSource={list.data ?? []} pagination={false} columns={[{ title: '申请商户', dataIndex: 'merchantName' }, { title: '类目', dataIndex: 'category' }, { title: '联系人', render: (_, item: OpsOnboarding) => `${item.contactName ?? '-'} ${item.contactMobileMasked ?? ''}` }, { title: '提交时间', dataIndex: 'createdAt' }, { title: '操作', render: (_, item: OpsOnboarding) => <Space><Popconfirm title="审核通过后将启用商户，继续吗？" onConfirm={() => void approve(item)}><Button size="small" type="primary">通过</Button></Popconfirm><Button size="small" danger onClick={() => setSelected(item)}>拒绝</Button></Space> }]} /><Modal open={Boolean(selected)} title="拒绝入驻申请" onOk={() => void reject()} onCancel={() => setSelected(undefined)}><Input.TextArea value={reason} onChange={event => setReason(event.target.value)} maxLength={200} placeholder="拒绝原因（必填）" /></Modal></Card>;
}

function Notifications() {
  const client = useQueryClient(); const list = useQuery({ queryKey: ['ops', 'notifications'], queryFn: opsMerchantApi.notifications }); const retry = async (item: OpsNotification) => { try { await opsMerchantApi.retryNotification(item.notificationId); await client.invalidateQueries({ queryKey: ['ops', 'notifications'] }); message.success('已提交一次人工重试'); } catch (error) { message.error(error instanceof Error ? error.message : '重试失败'); } };
  return <Card title="商户通知"><Table rowKey="notificationId" loading={list.isPending} dataSource={list.data ?? []} pagination={false} columns={[{ title: '类型', dataIndex: 'type' }, { title: '状态', render: (_, item: OpsNotification) => <Tag color={item.status === 'SUCCEEDED' ? 'green' : item.status === 'FAILED' ? 'red' : 'gold'}>{item.status}</Tag> }, { title: '次数', dataIndex: 'attempts' }, { title: '响应摘要', dataIndex: 'responseSummary' }, { title: '操作', render: (_, item: OpsNotification) => item.status === 'FAILED' ? <Popconfirm title="立即执行一次人工重试？" onConfirm={() => void retry(item)}><Button size="small">人工重试</Button></Popconfirm> : null }]} /><Typography.Paragraph type="secondary" style={{ marginTop: 16 }}>人工重试不会重置自动重试次数；失败后仍按后端退避策略进入人工处理。</Typography.Paragraph></Card>;
}

function Todos() { const navigate = useNavigate(); const todos = useQuery({ queryKey: ['ops', 'todos'], queryFn: opsMerchantApi.todos }); return <Space direction="vertical" size="middle" style={{ width: '100%' }}><Typography.Title level={3}>待处理事项</Typography.Title>{todos.isError ? <Alert type="error" showIcon title="待办加载失败" /> : <Space wrap><Card><Statistic title="待审核入驻" value={todos.data?.pendingOnboardings ?? 0} suffix="项" /><Button type="link" onClick={() => navigate('/onboardings')}>去审核</Button></Card><Card><Statistic title="通知人工处理" value={todos.data?.notificationsAwaitingManualRetry ?? 0} suffix="项" /><Button type="link" onClick={() => navigate('/notifications')}>去处理</Button></Card></Space>}</Space>; }
